-- LINE News Bot: Contact database schema
-- Database: PostgreSQL
-- Compatible with Prisma models Organization and Contact
-- Run once on the new database. Safe to run again when the existing schema matches.

BEGIN;

-- Prisma enum: ContactRole
DO $$
BEGIN
    CREATE TYPE "ContactRole" AS ENUM ('PRIMARY', 'SECONDARY');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

-- Prisma enum: ContactType
DO $$
BEGIN
    CREATE TYPE "ContactType" AS ENUM (
        'GENERAL',
        'EMERGENCY',
        'MAINTENANCE',
        'IT_SUPPORT',
        'LAB_SUPPORT',
        'VENDOR',
        'OTHER'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END
$$;

-- Prisma model: Organization
CREATE TABLE IF NOT EXISTS organizations (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    code        TEXT UNIQUE,
    created_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Prisma model: Contact
CREATE TABLE IF NOT EXISTS contacts (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id     INTEGER NOT NULL,
    name                TEXT NOT NULL,
    phone               TEXT,
    email               TEXT,
    line_id             TEXT,
    position            TEXT,
    contact_role        "ContactRole" NOT NULL DEFAULT 'SECONDARY',
    contact_type        "ContactType" NOT NULL DEFAULT 'GENERAL',
    is_available_24h    BOOLEAN NOT NULL DEFAULT false,
    note                TEXT,
    created_at          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT contacts_organization_id_fkey
        FOREIGN KEY (organization_id)
        REFERENCES organizations(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- Prisma @@index definitions
CREATE INDEX IF NOT EXISTS contacts_organization_id_idx
    ON contacts(organization_id);

CREATE INDEX IF NOT EXISTS contacts_contact_role_idx
    ON contacts(contact_role);

CREATE INDEX IF NOT EXISTS contacts_contact_type_idx
    ON contacts(contact_type);

-- Keep updated_at correct even when records are changed outside Prisma.
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS organizations_set_updated_at ON organizations;
CREATE TRIGGER organizations_set_updated_at
BEFORE UPDATE ON organizations
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS contacts_set_updated_at ON contacts;
CREATE TRIGGER contacts_set_updated_at
BEFORE UPDATE ON contacts
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMIT;

-- Verification queries (read-only)
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('organizations', 'contacts')
ORDER BY table_name;

SELECT
    (SELECT COUNT(*) FROM organizations) AS organization_count,
    (SELECT COUNT(*) FROM contacts) AS contact_count;
